environment:
  matrix:
  - TARGET: x86_64-pc-windows-msvc
  - TARGET: i686-pc-windows-msvc
  - TARGET: i686-pc-windows-gnu
install:
  - ps: Start-FileDownload "https://static.rust-lang.org/dist/rust-nightly-${env:TARGET}.exe"
  - rust-nightly-%TARGET%.exe /VERYSILENT /NORESTART /DIR="C:\Program Files (x86)\Rust"
  - mkdir C:\Cbc
  - ps: Start-FileDownload "https://bintray.com/coin-or/download/download_file?file_path=Cbc-2.9-win32-msvc14.zip" -FileName "C:\Cbc\Cbc-2.9.zip"
  - 7z x C:\Cbc\Cbc-2.9.zip -o"C:\Cbc\"
  - SET PATH=%PATH%;C:\Cbc\bin
  - SET LIB=%LIB%;C:\Cbc\lib
  - SET PATH=%PATH%;C:\Program Files (x86)\Rust\bin
  - SET PATH=%PATH%;C:\MinGW\bin
  - rustc -V
  - cargo -V

build: off

test_script:
  - cargo build
  - cargo test --verbose
